from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_") or "Schema"


def _type_name(ref: str) -> str:
    return _name(ref.rsplit("/", 1)[-1])


def _schema_type(schema: dict[str, Any]) -> str:
    if not schema:
        return "null"
    if "$ref" in schema:
        return _type_name(schema["$ref"])
    if "anyOf" in schema:
        members = [_schema_type(item) for item in schema["anyOf"]]
        if len(members) > 1 and "null" not in members:
            members.append("null")
        return " | ".join(dict.fromkeys(members))
    if "oneOf" in schema:
        members = [_schema_type(item) for item in schema["oneOf"]]
        if len(members) > 1 and "null" not in members:
            members.append("null")
        return " | ".join(dict.fromkeys(members))
    if schema.get("type") == "array":
        return f"Array<{_schema_type(schema.get('items', {}))}>"
    if schema.get("type") == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            additional = schema.get("additionalProperties")
            return "Record<string, unknown>" if additional is not False else "Record<string, never>"
        fields = []
        for key, value in properties.items():
            optional = "" if key in required else "?"
            fields.append(f"{_name(key)}{optional}: {_schema_type(value)}")
        return "{ " + "; ".join(fields) + " }"
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(
        schema.get("type"), "unknown"
    )


def _operation_type(operation: dict[str, Any]) -> str:
    responses = operation.get("responses", {})
    success = next(
        (value for key, value in responses.items() if str(key).startswith("2")),
        {},
    )
    response_schema = (
        success.get("content", {}).get("application/json", {}).get("schema", {})
        if isinstance(success, dict)
        else {}
    )
    return _schema_type(response_schema)


def generate_openapi() -> None:
    from apps.api.app.main import app

    contract = app.openapi()
    destination = ROOT / "docs" / "openapi.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8")

    schemas = contract.get("components", {}).get("schemas", {})
    lines = [
        "// Generated from docs/openapi.json by scripts/generate_openapi_types.py.",
        "// Do not edit this file by hand.",
        "",
    ]
    for name, schema in schemas.items():
        lines.append(f"export type {_name(name)} = {_schema_type(schema)};")
    lines.extend(["", "export type paths = {"])
    for path, path_item in contract.get("paths", {}).items():
        if not isinstance(path_item, dict):
            continue
        operations = [
            f"  {method}: { _operation_type(operation) }"
            for method, operation in path_item.items()
            if method in {"get", "post", "put", "patch", "delete"} and isinstance(operation, dict)
        ]
        if operations:
            lines.append(f"  {_name(path)}: {{")
            lines.extend(f"    {line.strip()};" for line in operations)
            lines.append("  };")
    lines.extend(["};", ""])
    types_destination = ROOT / "apps" / "web" / "src" / "lib" / "api" / "generated" / "types.ts"
    types_destination.parent.mkdir(parents=True, exist_ok=True)
    types_destination.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate_openapi()
